output "hcp_project_id" {
  description = "HCP project ID used for Ezra resources."
  value       = local.hcp_project_id
}

output "hcp_vault_cluster_id" {
  description = "HCP Vault cluster ID when enable_hcp_vault is true."
  value       = var.enable_hcp_vault ? hcp_vault_cluster.ezra[0].cluster_id : null
}

output "hcp_vault_public_endpoint_url" {
  description = "Public Vault endpoint URL when available."
  value       = var.enable_hcp_vault ? hcp_vault_cluster.ezra[0].vault_public_endpoint_url : null
}

output "hcp_vault_addr" {
  description = "Vault address to use for bootstrap operations."
  value       = var.enable_hcp_vault ? hcp_vault_cluster.ezra[0].vault_public_endpoint_url : null
}

output "hcp_vault_admin_token" {
  description = "Vault admin token generated by HCP for bootstrap operations."
  value       = var.enable_hcp_vault && var.create_hcp_vault_admin_token ? hcp_vault_cluster_admin_token.ezra[0].token : null
  sensitive   = true
}

output "tfe_organization_name" {
  description = "HCP Terraform organization used for backend-state resources."
  value       = local.tfe_organization_name
}

output "tfe_project_id" {
  description = "HCP Terraform project ID for backend-state workspaces."
  value       = tfe_project.backend_state.id
}

output "tfe_workspace_ids" {
  description = "Workspace IDs keyed by workspace name."
  value       = { for name, ws in tfe_workspace.terraform_projects : name => ws.id }
}
